version: "3"
services:
  api:
    image: node
    ports:
      - 3000:3000
      - 9229:9229
    working_dir: /usr/app
    volumes:
      - .:/usr/app/
      - /node_modules
    command: bash -c "npm instal && npm run start:debug"
    restart: always
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
  db_test:
    image: postgres
    ports:
      - 65432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    restart: always
